version: '3.3'
services:
  db:
    container_name: "hire_db"
    image: "postgres:15.2"
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: "hire_db"
      POSTGRES_USER: "hire_user"
      POSTGRES_PASSWORD: "hire_password"
    volumes:
      - 'data:/var/lib/postgresql/data'
  jenkins:
    image: 'jenkins/jenkins:lts'
    privileged: true
    user: 'root'
    ports:
     - "8080:8080"
     - "50000:50000"
    container_name: 'jenkins'
    volumes:
      - 'jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  data:
  jenkins: