version: '3.3'
services:
  db:
    container_name: "hire_db"
    image: "postgres"
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: "hire_db"
      POSTGRES_USER: "hire_user"
      POSTGRES_PASSWORD: "hire_password"
    volumes:
      - 'data:/var/lib/postgresql/data'
# Names our volume
volumes:
  data: