version: '3.3'
services:
  db:
    container_name: "hire_db"
    image: "postgres"
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: "hire_db"
      POSTGRES_USER: "hire_user"
      POSTGRES_PASSWORD: "hire_password"
    volumes:
      - 'data:/var/lib/postgresql/data'
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:5.5.1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
volumes:
  data: