INSERT INTO countries (id, code, name, dial_code, currency_name, currency_symbol, currency_code, active,
                       has_postal_code)
VALUES (1, 'AF', 'Afghanistan', 93, 'Afghan afghani', 'Ø‹', 'AFN', false, true),
       (2, 'AL', 'Albania', 355, 'Albanian lek', 'L', 'ALL', false, true),
       (3, 'DZ', 'Algeria', 213, 'Algerian dinar', 'Ø¯.Ø¬', 'DZD', false, true),
       (4, 'AS', 'American Samoa', 1684, '', '', '', false, true),
       (5, 'AD', 'Andorra', 376, 'Euro', 'â‚¬', 'EUR', false, true),
       (6, 'AO', 'Angola', 244, 'Angolan kwanza', 'Kz', 'AOA', false, true),
       (7, 'AI', 'Anguilla', 1264, 'East Caribbean dolla', '$', 'XCD', false, true),
       (8, 'AQ', 'Antarctica', 0, '', '', '', false, true),
       (9, 'AG', 'Antigua And Barbuda', 1268, 'East Caribbean dolla', '$', 'XCD', false, true),
       (10, 'AR', 'Argentina', 54, 'Argentine peso', '$', 'ARS', false, true),
       (11, 'AM', 'Armenia', 374, 'Armenian dram', '', 'AMD', false, true),
       (12, 'AW', 'Aruba', 297, 'Aruban florin', 'Æ’', 'AWG', false, true),
       (13, 'AU', 'Australia', 61, 'Australian dollar', '$', 'AUD', false, true),
       (14, 'AT', 'Austria', 43, 'Euro', 'â‚¬', 'EUR', false, true),
       (15, 'AZ', 'Azerbaijan', 994, 'Azerbaijani manat', '', 'AZN', false, true),
       (16, 'BS', 'Bahamas The', 1242, '', '', '', false, true),
       (17, 'BH', 'Bahrain', 973, 'Bahraini dinar', '.Ø¯.Ø¨', 'BHD', false, true),
       (18, 'BD', 'Bangladesh', 880, 'Bangladeshi taka', 'à§³', 'BDT', false, true),
       (19, 'BB', 'Barbados', 1246, 'Barbadian dollar', '$', 'BBD', false, true),
       (20, 'BY', 'Belarus', 375, 'Belarusian ruble', 'Br', 'BYR', false, true),
       (21, 'BE', 'Belgium', 32, 'Euro', 'â‚¬', 'EUR', false, true),
       (22, 'BZ', 'Belize', 501, 'Belize dollar', '$', 'BZD', false, true),
       (23, 'BJ', 'Benin', 229, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (24, 'BM', 'Bermuda', 1441, 'Bermudian dollar', '$', 'BMD', false, true),
       (25, 'BT', 'Bhutan', 975, 'Bhutanese ngultrum', 'Nu.', 'BTN', false, true),
       (26, 'BO', 'Bolivia', 591, 'Bolivian boliviano', 'Bs.', 'BOB', false, true),
       (27, 'BA', 'Bosnia and Herzegovina', 387, 'Bosnia and Herzegovi', 'KM or ÐšÐœ', 'BAM', false, true),
       (28, 'BW', 'Botswana', 267, 'Botswana pula', 'P', 'BWP', false, true),
       (29, 'BV', 'Bouvet Island', 0, '', '', '', false, true),
       (30, 'BR', 'Brazil', 55, 'Brazilian real', 'R$', 'BRL', false, true),
       (31, 'IO', 'British Indian Ocean Territory', 246, 'United States dollar', '$', 'USD', false, true),
       (32, 'BN', 'Brunei', 673, 'Brunei dollar', '$', 'BND', false, true),
       (33, 'BG', 'Bulgaria', 359, 'Bulgarian lev', 'Ð»Ð²', 'BGN', false, true),
       (34, 'BF', 'Burkina Faso', 226, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (35, 'BI', 'Burundi', 257, 'Burundian franc', 'Fr', 'BIF', false, true),
       (36, 'KH', 'Cambodia', 855, 'Cambodian riel', 'áŸ›', 'KHR', false, true),
       (37, 'CM', 'Cameroon', 237, 'Central African CFA ', 'Fr', 'XAF', false, true),
       (38, 'CA', 'Canada', 1, 'Canadian dollar', '$', 'CAD', false, true),
       (39, 'CV', 'Cape Verde', 238, 'Cape Verdean escudo', 'Esc or $', 'CVE', false, true),
       (40, 'KY', 'Cayman Islands', 1345, 'Cayman Islands dolla', '$', 'KYD', false, true),
       (41, 'CF', 'Central African Republic', 236, 'Central African CFA ', 'Fr', 'XAF', false, true),
       (42, 'TD', 'Chad', 235, 'Central African CFA ', 'Fr', 'XAF', false, true),
       (43, 'CL', 'Chile', 56, 'Chilean peso', '$', 'CLP', false, true),
       (44, 'CN', 'China', 86, 'Chinese yuan', 'Â¥ or å…ƒ', 'CNY', false, true),
       (45, 'CX', 'Christmas Island', 61, '', '', '', false, true),
       (46, 'CC', 'Cocos (Keeling) Islands', 672, 'Australian dollar', '$', 'AUD', false, true),
       (47, 'CO', 'Colombia', 57, 'Colombian peso', '$', 'COP', false, true),
       (48, 'KM', 'Comoros', 269, 'Comorian franc', 'Fr', 'KMF', false, true),
       (49, 'CG', 'Congo', 242, '', '', '', false, true),
       (50, 'CD', 'RD Congo', 243, '', '', '', true, false),
       (51, 'CK', 'Cook Islands', 682, 'New Zealand dollar', '$', 'NZD', false, true),
       (52, 'CR', 'Costa Rica', 506, 'Costa Rican colÃ³n', 'â‚¡', 'CRC', false, true),
       (53, 'CI', 'Cote D''Ivoire (Ivory Coast)', 225, '', '', '', false, true),
       (54, 'HR', 'Croatia (Hrvatska)', 385, '', '', '', false, true),
       (55, 'CU', 'Cuba', 53, 'Cuban convertible pe', '$', 'CUC', false, true),
       (56, 'CY', 'Cyprus', 357, 'Euro', 'â‚¬', 'EUR', false, true),
       (57, 'CZ', 'Czech Republic', 420, 'Czech koruna', 'KÄ', 'CZK', false, true),
       (58, 'DK', 'Denmark', 45, 'Danish krone', 'kr', 'DKK', false, true),
       (59, 'DJ', 'Djibouti', 253, 'Djiboutian franc', 'Fr', 'DJF', false, true),
       (60, 'DM', 'Dominica', 1767, 'East Caribbean dolla', '$', 'XCD', false, true),
       (61, 'DO', 'Dominican Republic', 1809, 'Dominican peso', '$', 'DOP', false, true),
       (62, 'TP', 'East Timor', 670, 'United States dollar', '$', 'USD', false, true),
       (63, 'EC', 'Ecuador', 593, 'United States dollar', '$', 'USD', false, true),
       (64, 'EG', 'Egypt', 20, 'Egyptian pound', 'Â£ or Ø¬.Ù…', 'EGP', false, true),
       (65, 'SV', 'El Salvador', 503, 'United States dollar', '$', 'USD', false, true),
       (66, 'GQ', 'Equatorial Guinea', 240, 'Central African CFA ', 'Fr', 'XAF', false, true),
       (67, 'ER', 'Eritrea', 291, 'Eritrean nakfa', 'Nfk', 'ERN', false, true),
       (68, 'EE', 'Estonia', 372, 'Euro', 'â‚¬', 'EUR', false, true),
       (69, 'ET', 'Ethiopia', 251, 'Ethiopian birr', 'Br', 'ETB', false, true),
       (70, 'XA', 'External Territories of Australia', 61, '', '', '', false, true),
       (71, 'FK', 'Falkland Islands', 500, 'Falkland Islands pou', 'Â£', 'FKP', false, true),
       (72, 'FO', 'Faroe Islands', 298, 'Danish krone', 'kr', 'DKK', false, true),
       (73, 'FJ', 'Fiji Islands', 679, '', '', '', false, true),
       (74, 'FI', 'Finland', 358, 'Euro', 'â‚¬', 'EUR', false, true),
       (75, 'FR', 'France', 33, 'Euro', 'â‚¬', 'EUR', false, true),
       (76, 'GF', 'French Guiana', 594, '', '', '', false, true),
       (77, 'PF', 'French Polynesia', 689, 'CFP franc', 'Fr', 'XPF', false, true),
       (78, 'TF', 'French Southern Territories', 0, '', '', '', false, true),
       (79, 'GA', 'Gabon', 241, 'Central African CFA ', 'Fr', 'XAF', false, true),
       (80, 'GM', 'Gambia The', 220, '', '', '', false, true),
       (81, 'GE', 'Georgia', 995, 'Georgian lari', 'áƒš', 'GEL', false, true),
       (82, 'DE', 'Germany', 49, 'Euro', 'â‚¬', 'EUR', false, true),
       (83, 'GH', 'Ghana', 233, 'Ghana cedi', 'â‚µ', 'GHS', false, true),
       (84, 'GI', 'Gibraltar', 350, 'Gibraltar pound', 'Â£', 'GIP', false, true),
       (85, 'GR', 'Greece', 30, 'Euro', 'â‚¬', 'EUR', false, true),
       (86, 'GL', 'Greenland', 299, '', '', '', false, true),
       (87, 'GD', 'Grenada', 1473, 'East Caribbean dolla', '$', 'XCD', false, true),
       (88, 'GP', 'Guadeloupe', 590, '', '', '', false, true),
       (89, 'GU', 'Guam', 1671, '', '', '', false, true),
       (90, 'GT', 'Guatemala', 502, 'Guatemalan quetzal', 'Q', 'GTQ', false, true),
       (91, 'XU', 'Guernsey and Alderney', 44, '', '', '', false, true),
       (92, 'GN', 'Guinea', 224, 'Guinean franc', 'Fr', 'GNF', false, true),
       (93, 'GW', 'Guinea-Bissau', 245, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (94, 'GY', 'Guyana', 592, 'Guyanese dollar', '$', 'GYD', false, true),
       (95, 'HT', 'Haiti', 509, 'Haitian gourde', 'G', 'HTG', false, true),
       (96, 'HM', 'Heard and McDonald Islands', 0, '', '', '', false, true),
       (97, 'HN', 'Honduras', 504, 'Honduran lempira', 'L', 'HNL', false, true),
       (98, 'HK', 'Hong Kong S.A.R.', 852, '', '', '', false, true),
       (99, 'HU', 'Hungary', 36, 'Hungarian forint', 'Ft', 'HUF', false, true),
       (100, 'IS', 'Iceland', 354, 'Icelandic krÃ³na', 'kr', 'ISK', false, true),
       (101, 'IN', 'India', 91, 'Indian rupee', 'â‚¹', 'INR', false, true),
       (102, 'ID', 'Indonesia', 62, 'Indonesian rupiah', 'Rp', 'IDR', false, true),
       (103, 'IR', 'Iran', 98, 'Iranian rial', 'ï·¼', 'IRR', false, true),
       (104, 'IQ', 'Iraq', 964, 'Iraqi dinar', 'Ø¹.Ø¯', 'IQD', false, true),
       (105, 'IE', 'Ireland', 353, 'Euro', 'â‚¬', 'EUR', false, true),
       (106, 'IL', 'Israel', 972, 'Israeli new shekel', 'â‚ª', 'ILS', false, true),
       (107, 'IT', 'Italy', 39, 'Euro', 'â‚¬', 'EUR', false, true),
       (108, 'JM', 'Jamaica', 1876, 'Jamaican dollar', '$', 'JMD', false, true),
       (109, 'JP', 'Japan', 81, 'Japanese yen', 'Â¥', 'JPY', false, true),
       (110, 'XJ', 'Jersey', 44, 'British pound', 'Â£', 'GBP', false, true),
       (111, 'JO', 'Jordan', 962, 'Jordanian dinar', 'Ø¯.Ø§', 'JOD', false, true),
       (112, 'KZ', 'Kazakhstan', 7, 'Kazakhstani tenge', '', 'KZT', false, true),
       (113, 'KE', 'Kenya', 254, 'Kenyan shilling', 'Sh', 'KES', false, true),
       (114, 'KI', 'Kiribati', 686, 'Australian dollar', '$', 'AUD', false, true),
       (115, 'KP', 'Korea North', 850, '', '', '', false, true),
       (116, 'KR', 'Korea South', 82, '', '', '', false, true),
       (117, 'KW', 'Kuwait', 965, 'Kuwaiti dinar', 'Ø¯.Ùƒ', 'KWD', false, true),
       (118, 'KG', 'Kyrgyzstan', 996, 'Kyrgyzstani som', 'Ð»Ð²', 'KGS', false, true),
       (119, 'LA', 'Laos', 856, 'Lao kip', 'â‚­', 'LAK', false, true),
       (120, 'LV', 'Latvia', 371, 'Euro', 'â‚¬', 'EUR', false, true),
       (121, 'LB', 'Lebanon', 961, 'Lebanese pound', 'Ù„.Ù„', 'LBP', false, true),
       (122, 'LS', 'Lesotho', 266, 'Lesotho loti', 'L', 'LSL', false, true),
       (123, 'LR', 'Liberia', 231, 'Liberian dollar', '$', 'LRD', false, true),
       (124, 'LY', 'Libya', 218, 'Libyan dinar', 'Ù„.Ø¯', 'LYD', false, true),
       (125, 'LI', 'Liechtenstein', 423, 'Swiss franc', 'Fr', 'CHF', false, true),
       (126, 'LT', 'Lithuania', 370, 'Euro', 'â‚¬', 'EUR', false, true),
       (127, 'LU', 'Luxembourg', 352, 'Euro', 'â‚¬', 'EUR', false, true),
       (128, 'MO', 'Macau S.A.R.', 853, '', '', '', false, true),
       (129, 'MK', 'Macedonia', 389, '', '', '', false, true),
       (130, 'MG', 'Madagascar', 261, 'Malagasy ariary', 'Ar', 'MGA', false, true),
       (131, 'MW', 'Malawi', 265, 'Malawian kwacha', 'MK', 'MWK', false, true),
       (132, 'MY', 'Malaysia', 60, 'Malaysian ringgit', 'RM', 'MYR', false, true),
       (133, 'MV', 'Maldives', 960, 'Maldivian rufiyaa', '.Þƒ', 'MVR', false, true),
       (134, 'ML', 'Mali', 223, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (135, 'MT', 'Malta', 356, 'Euro', 'â‚¬', 'EUR', false, true),
       (136, 'XM', 'Man (Isle of)', 44, '', '', '', false, true),
       (137, 'MH', 'Marshall Islands', 692, 'United States dollar', '$', 'USD', false, true),
       (138, 'MQ', 'Martinique', 596, '', '', '', false, true),
       (139, 'MR', 'Mauritania', 222, 'Mauritanian ouguiya', 'UM', 'MRO', false, true),
       (140, 'MU', 'Mauritius', 230, 'Mauritian rupee', 'â‚¨', 'MUR', false, true),
       (141, 'YT', 'Mayotte', 269, '', '', '', false, true),
       (142, 'MX', 'Mexico', 52, 'Mexican peso', '$', 'MXN', false, true),
       (143, 'FM', 'Micronesia', 691, 'Micronesian dollar', '$', '', false, true),
       (144, 'MD', 'Moldova', 373, 'Moldovan leu', 'L', 'MDL', false, true),
       (145, 'MC', 'Monaco', 377, 'Euro', 'â‚¬', 'EUR', false, true),
       (146, 'MN', 'Mongolia', 976, 'Mongolian tÃ¶grÃ¶g', 'â‚®', 'MNT', false, true),
       (147, 'MS', 'Montserrat', 1664, 'East Caribbean dolla', '$', 'XCD', false, true),
       (148, 'MA', 'Morocco', 212, 'Moroccan dirham', 'Ø¯.Ù….', 'MAD', false, true),
       (149, 'MZ', 'Mozambique', 258, 'Mozambican metical', 'MT', 'MZN', false, true),
       (150, 'MM', 'Myanmar', 95, 'Burmese kyat', 'Ks', 'MMK', false, true),
       (151, 'NA', 'Namibia', 264, 'Namibian dollar', '$', 'NAD', false, true),
       (152, 'NR', 'Nauru', 674, 'Australian dollar', '$', 'AUD', false, true),
       (153, 'NP', 'Nepal', 977, 'Nepalese rupee', 'â‚¨', 'NPR', false, true),
       (154, 'AN', 'Netherlands Antilles', 599, '', '', '', false, true),
       (155, 'NL', 'Netherlands The', 31, '', '', '', false, true),
       (156, 'NC', 'New Caledonia', 687, 'CFP franc', 'Fr', 'XPF', false, true),
       (157, 'NZ', 'New Zealand', 64, 'New Zealand dollar', '$', 'NZD', false, true),
       (158, 'NI', 'Nicaragua', 505, 'Nicaraguan cÃ³rdoba', 'C$', 'NIO', false, true),
       (159, 'NE', 'Niger', 227, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (160, 'NG', 'Nigeria', 234, 'Nigerian naira', 'â‚¦', 'NGN', false, true),
       (161, 'NU', 'Niue', 683, 'New Zealand dollar', '$', 'NZD', false, true),
       (162, 'NF', 'Norfolk Island', 672, '', '', '', false, true),
       (163, 'MP', 'Northern Mariana Islands', 1670, '', '', '', false, true),
       (164, 'NO', 'Norway', 47, 'Norwegian krone', 'kr', 'NOK', false, true),
       (165, 'OM', 'Oman', 968, 'Omani rial', 'Ø±.Ø¹.', 'OMR', false, true),
       (166, 'PK', 'Pakistan', 92, 'Pakistani rupee', 'â‚¨', 'PKR', false, true),
       (167, 'PW', 'Palau', 680, 'Palauan dollar', '$', '', false, true),
       (168, 'PS', 'Palestinian Territory Occupied', 970, '', '', '', false, true),
       (169, 'PA', 'Panama', 507, 'Panamanian balboa', 'B/.', 'PAB', false, true),
       (170, 'PG', 'Papua new Guinea', 675, 'Papua New Guinean ki', 'K', 'PGK', false, true),
       (171, 'PY', 'Paraguay', 595, 'Paraguayan guaranÃ­', 'â‚²', 'PYG', false, true),
       (172, 'PE', 'Peru', 51, 'Peruvian nuevo sol', 'S/.', 'PEN', false, true),
       (173, 'PH', 'Philippines', 63, 'Philippine peso', 'â‚±', 'PHP', false, true),
       (174, 'PN', 'Pitcairn Island', 0, '', '', '', false, true),
       (175, 'PL', 'Poland', 48, 'Polish zÅ‚oty', 'zÅ‚', 'PLN', false, true),
       (176, 'PT', 'Portugal', 351, 'Euro', 'â‚¬', 'EUR', false, true),
       (177, 'PR', 'Puerto Rico', 1787, '', '', '', false, true),
       (178, 'QA', 'Qatar', 974, 'Qatari riyal', 'Ø±.Ù‚', 'QAR', false, true),
       (179, 'RE', 'Reunion', 262, '', '', '', false, true),
       (180, 'RO', 'Romania', 40, 'Romanian leu', 'lei', 'RON', false, true),
       (181, 'RU', 'Russia', 70, 'Russian ruble', '', 'RUB', false, true),
       (182, 'RW', 'Rwanda', 250, 'Rwandan franc', 'Fr', 'RWF', false, true),
       (183, 'SH', 'Saint Helena', 290, 'Saint Helena pound', 'Â£', 'SHP', false, true),
       (184, 'KN', 'Saint Kitts And Nevis', 1869, 'East Caribbean dolla', '$', 'XCD', false, true),
       (185, 'LC', 'Saint Lucia', 1758, 'East Caribbean dolla', '$', 'XCD', false, true),
       (186, 'PM', 'Saint Pierre and Miquelon', 508, '', '', '', false, true),
       (187, 'VC', 'Saint Vincent And The Grenadines', 1784, 'East Caribbean dolla', '$', 'XCD', false, true),
       (188, 'WS', 'Samoa', 684, 'Samoan tÄlÄ', 'T', 'WST', false, true),
       (189, 'SM', 'San Marino', 378, 'Euro', 'â‚¬', 'EUR', false, true),
       (190, 'ST', 'Sao Tome and Principe', 239, 'SÃ£o TomÃ© and PrÃ­ncip', 'Db', 'STD', false, true),
       (191, 'SA', 'Saudi Arabia', 966, 'Saudi riyal', 'Ø±.Ø³', 'SAR', false, true),
       (192, 'SN', 'Senegal', 221, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (193, 'RS', 'Serbia', 381, 'Serbian dinar', 'Ð´Ð¸Ð½. or din.', 'RSD', false, true),
       (194, 'SC', 'Seychelles', 248, 'Seychellois rupee', 'â‚¨', 'SCR', false, true),
       (195, 'SL', 'Sierra Leone', 232, 'Sierra Leonean leone', 'Le', 'SLL', false, true),
       (196, 'SG', 'Singapore', 65, 'Brunei dollar', '$', 'BND', false, true),
       (197, 'SK', 'Slovakia', 421, 'Euro', 'â‚¬', 'EUR', false, true),
       (198, 'SI', 'Slovenia', 386, 'Euro', 'â‚¬', 'EUR', false, true),
       (199, 'XG', 'Smaller Territories of the UK', 44, '', '', '', false, true),
       (200, 'SB', 'Solomon Islands', 677, 'Solomon Islands doll', '$', 'SBD', false, true),
       (201, 'SO', 'Somalia', 252, 'Somali shilling', 'Sh', 'SOS', false, true),
       (202, 'ZA', 'South Africa', 27, 'South African rand', 'R', 'ZAR', false, true),
       (203, 'GS', 'South Georgia', 0, '', '', '', false, true),
       (204, 'SS', 'South Sudan', 211, 'South Sudanese pound', 'Â£', 'SSP', false, true),
       (205, 'ES', 'Spain', 34, 'Euro', 'â‚¬', 'EUR', false, true),
       (206, 'LK', 'Sri Lanka', 94, 'Sri Lankan rupee', 'Rs or à¶»à·”', 'LKR', false, true),
       (207, 'SD', 'Sudan', 249, 'Sudanese pound', 'Ø¬.Ø³.', 'SDG', false, true),
       (208, 'SR', 'Suriname', 597, 'Surinamese dollar', '$', 'SRD', false, true),
       (209, 'SJ', 'Svalbard And Jan Mayen Islands', 47, '', '', '', false, true),
       (210, 'SZ', 'Swaziland', 268, 'Swazi lilangeni', 'L', 'SZL', false, true),
       (211, 'SE', 'Sweden', 46, 'Swedish krona', 'kr', 'SEK', false, true),
       (212, 'CH', 'Switzerland', 41, 'Swiss franc', 'Fr', 'CHF', false, true),
       (213, 'SY', 'Syria', 963, 'Syrian pound', 'Â£ or Ù„.Ø³', 'SYP', false, true),
       (214, 'TW', 'Taiwan', 886, 'New Taiwan dollar', '$', 'TWD', false, true),
       (215, 'TJ', 'Tajikistan', 992, 'Tajikistani somoni', 'Ð…Ðœ', 'TJS', false, true),
       (216, 'TZ', 'Tanzania', 255, 'Tanzanian shilling', 'Sh', 'TZS', false, true),
       (217, 'TH', 'Thailand', 66, 'Thai baht', 'à¸¿', 'THB', false, true),
       (218, 'TG', 'Togo', 228, 'West African CFA fra', 'Fr', 'XOF', false, true),
       (219, 'TK', 'Tokelau', 690, '', '', '', false, true),
       (220, 'TO', 'Tonga', 676, 'Tongan paÊ»anga', 'T$', 'TOP', false, true),
       (221, 'TT', 'Trinidad And Tobago', 1868, 'Trinidad and Tobago ', '$', 'TTD', false, true),
       (222, 'TN', 'Tunisia', 216, 'Tunisian dinar', 'Ø¯.Øª', 'TND', false, true),
       (223, 'TR', 'Turkey', 90, 'Turkish lira', '', 'TRY', false, true),
       (224, 'TM', 'Turkmenistan', 7370, 'Turkmenistan manat', 'm', 'TMT', false, true),
       (225, 'TC', 'Turks And Caicos Islands', 1649, 'United States dollar', '$', 'USD', false, true),
       (226, 'TV', 'Tuvalu', 688, 'Australian dollar', '$', 'AUD', false, true),
       (227, 'UG', 'Uganda', 256, 'Ugandan shilling', 'Sh', 'UGX', false, true),
       (228, 'UA', 'Ukraine', 380, 'Ukrainian hryvnia', 'â‚´', 'UAH', false, true),
       (229, 'AE', 'United Arab Emirates', 971, 'United Arab Emirates', 'Ø¯.Ø¥', 'AED', false, true),
       (230, 'GB', 'United Kingdom', 44, 'British pound', 'Â£', 'GBP', false, true),
       (231, 'US', 'United States', 1, 'United States dollar', '$', 'USD', false, true),
       (232, 'UM', 'United States Minor Outlying Islands', 1, '', '', '', false, true),
       (233, 'UY', 'Uruguay', 598, 'Uruguayan peso', '$', 'UYU', false, true),
       (234, 'UZ', 'Uzbekistan', 998, 'Uzbekistani som', '', 'UZS', false, true),
       (235, 'VU', 'Vanuatu', 678, 'Vanuatu vatu', 'Vt', 'VUV', false, true),
       (236, 'VA', 'Vatican City State (Holy See)', 39, '', '', '', false, true),
       (237, 'VE', 'Venezuela', 58, 'Venezuelan bolÃ­var', 'Bs F', 'VEF', false, true),
       (238, 'VN', 'Vietnam', 84, 'Vietnamese Ä‘á»“ng', 'â‚«', 'VND', false, true),
       (239, 'VG', 'Virgin Islands (British)', 1284, '', '', '', false, true),
       (240, 'VI', 'Virgin Islands (US)', 1340, '', '', '', false, true),
       (241, 'WF', 'Wallis And Futuna Islands', 681, '', '', '', false, true),
       (242, 'EH', 'Western Sahara', 212, '', '', '', false, true),
       (243, 'YE', 'Yemen', 967, 'Yemeni rial', 'ï·¼', 'YER', false, true),
       (244, 'YU', 'Yugoslavia', 38, '', '', '', false, true),
       (245, 'ZM', 'Zambia', 260, 'Zambian kwacha', 'ZK', 'ZMW', false, true),
       (246, 'ZW', 'Zimbabwe', 263, 'Botswana pula', 'P', 'BWP', false, true);
UPDATE countries
SET currency_code ='USD'
WHERE currency_code = ''
   OR currency_code IS NULL;