spring:
  datasource:
    url: "jdbc:postgresql://ec2-54-246-85-162.eu-west-1.compute.amazonaws.com:5432/dbq9flavg2nihv"
    username: "ctqebnxfvgvyma"
    password: "3f4ad6de86610bc516454de91a152000906daa33c35ffd98be128580f45ef505"
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  flyway:
    url: "jdbc:postgresql://ec2-54-246-85-162.eu-west-1.compute.amazonaws.com:5432/dbq9flavg2nihv"
    user: "ctqebnxfvgvyma"
    password: "3f4ad6de86610bc516454de91a152000906daa33c35ffd98be128580f45ef505"


