server:
  port: 8085
spring:
  application:
    name: "RemoteLabs-Hire-APi"
  datasource:
    url: "jdbc:postgresql://localhost:5436/hire_db"
    username: "hire_user"
    password: "hire_password"
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
  flyway:
    url: "jdbc:postgresql://localhost:5436/hire_db"
    user: "hire_user"
    password: "hire_password"



