spring:
  datasource:
    url: "jdbc:postgresql://ec2-52-18-116-67.eu-west-1.compute.amazonaws.com:5432/d36js1pph2v3hj"
    username: "ofnnpcaeykikqe"
    password: "531d007eec44b32aa2f2b580f97b822a03960944978d268657eefbc269787a8b"
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
  flyway:
    url: "jdbc:postgresql://ec2-52-18-116-67.eu-west-1.compute.amazonaws.com:5432/d36js1pph2v3hj"
    user: "ofnnpcaeykikqe"
    password: "531d007eec44b32aa2f2b580f97b822a03960944978d268657eefbc269787a8b"


