server:
  port: 8085
spring:
  application:
    name: "RemoteLabs-Hire-APi"
  datasource:
    url: "jdbc:postgresql://localhost:5436/hire_db"
    username: "hire_user"
    password: "hire_password"
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
jwt:
  secretKey: "2F413F4428472B4B6250655368566D597133743677397A244226452948404D63"



