server:
  port: 8081
spring:
  application:
    name: RemoteLabs-Hire-APi
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hire_db?autoreconnect=true
    username: "hire_user"
    password: "hire_password"
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true

