INSERT INTO tech_skills (id, name, logo_url, tags)
VALUES (1, 'Java',
        'https://banner2.cleanpng.com/20180621/jow/kisspng-plain-old-java-object-programming-language-compute-5b2b6405b39ad9.4848800015295703097357.jpg',
        'java, spring, boot, jee, j2m, android, servlet, applet'),
       (2, 'JavaScript', 'https://logodownload.org/wp-content/uploads/2022/04/javascript-logo-1.png', 'js, react, angular, vue, angularjs, jquery, vanilla'),
       (3, 'React',
        'https://e7.pngegg.com/pngimages/452/495/png-clipart-react-javascript-angularjs-ionic-github-text-logo-thumbnail.png','javascript, js, nextjs,'),
       (4, 'Angular', 'https://cdn.freebiesupply.com/logos/large/2x/angular-icon-1-logo-svg-vector.svg', 'javascript, js, typescript'),
       (5, 'Python',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Python_logo_01.svg/768px-Python_logo_01.svg.png','machine learning, ai, artificial intelligence'),
       (6, 'NodeJs', 'https://www.pngfind.com/pngs/m/683-6833893_node-js-logo-png-transparent-png.png', 'javascript, js, express, expressjs'),
       (7, 'Go Lang',
        'https://static.vecteezy.com/system/resources/previews/012/697/296/original/3d-golang-programming-language-logo-free-png.png','go'),
       (8, 'PHP',
        'https://banner2.cleanpng.com/20180904/xhu/kisspng-logo-image-computer-icons-php-portable-network-gra-william-davies-meng-mongodb-5b8e9698822d99.0636011515360713205332.jpg','php'),
       (9, 'Ruby On Rail',
        'https://img.favpng.com/4/13/16/ruby-on-rails-logo-programming-language-rubygems-png-favpng-WhQbCrZxcK4rVV4XP3x5JFYTF.jpg','ruby'),
       (10, 'Django', 'https://image.pngaaa.com/390/4169390-middle.png','python'),
       (11, 'Flask', 'https://www.pngfind.com/pngs/m/104-1044449_python-logo-clipart-drawing-flask-python-hd-png.png','python'),
       (12, 'Spring',
        'https://www.clipartmax.com/png/full/354-3543373_spring-framework-logo-svg-png-download-java-spring.png','java'),
       (13, 'SpringBoot', 'https://image.pngaaa.com/546/2459546-middle.png','java'),
       (14, 'C#',
        'https://e7.pngegg.com/pngimages/328/221/png-clipart-c-programming-language-logo-microsoft-visual-studio-net-framework-javascript-icon-purple-logo.png','asp.net, sharp csharp'),
       (15, 'C', 'https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png','c'),
       (16, 'C++',
        'https://e7.pngegg.com/pngimages/46/626/png-clipart-c-logo-the-c-programming-language-computer-icons-computer-programming-source-code-programming-miscellaneous-template.png','c++, ++'),
       (17, 'Laravel', 'https://image.pngaaa.com/634/3353634-middle.png', 'php, artisan, composer'),
       (18, 'Codeigniter', 'https://assets.stickpng.com/images/62a372286209494ec2b1706f.png', 'php'),
       (19, 'Symfony', 'https://cdn.freebiesupply.com/logos/large/2x/symfony-logo-png-transparent.png','php'),
       (20, 'Kotlin', 'https://cdn.freebiesupply.com/logos/thumbs/2x/kotlin-2-logo.png','java'),
       (21, 'ASP.NET', 'https://static.gunnarpeipman.com/wp-content/uploads/2020/09/aspnet-featured.png','c# sharp, csharp');