INSERT INTO technologies (id, name, logo_url)
VALUES (1, 'Java', 'https://www.citypng.com/public/uploads/small/11662223208mrscxxesmsb91zq9ubngbriqcijzc1j6q5u12serbmv9pimrziktl695capupvzdmhwhn7tozqooqkhcuxw9cejvc0fia2foatgb.png'),
       (2, 'JavaScript', 'https://logodownload.org/wp-content/uploads/2022/04/javascript-logo-1.png'),
       (3, 'React', 'https://www.pngitem.com/pimgs/m/664-6644509_icon-react-js-logo-hd-png-download.png'),
       (4, 'Angular', 'https://cdn.freebiesupply.com/logos/large/2x/angular-icon-1-logo-svg-vector.svg'),
       (5, 'Python', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Python_logo_01.svg/768px-Python_logo_01.svg.png'),
       (6, 'NodeJs', 'https://cdn.freebiesupply.com/logos/thumbs/2x/nodejs-1-logo.png'),
       (7, 'Go Lang', 'https://static.vecteezy.com/system/resources/previews/012/697/296/original/3d-golang-programming-language-logo-free-png.png'),
       (8, 'PHP', 'https://www.pngarts.com/files/6/PHP-Logo-PNG-Image-Background.png'),
       (9, 'Ruby On Rail', 'https://img.favpng.com/4/13/16/ruby-on-rails-logo-programming-language-rubygems-png-favpng-WhQbCrZxcK4rVV4XP3x5JFYTF.jpg'),
       (10, 'Django', 'https://www.pngkey.com/png/detail/416-4165142_tools-and-frameworks-django-framework-logo.png'),
       (11, 'Flask', 'https://www.nicolas-petitjean.com/wp-content/uploads/2018/11/flask.jpg'),
       (12, 'Spring', 'https://www.clipartmax.com/png/full/354-3543373_spring-framework-logo-svg-png-download-java-spring.png'),
       (13, 'SpringBoot', 'https://fiverr-res.cloudinary.com/t_main1,q_auto,f_auto/gigs2/235199913/original/b41fe097b365655d6553905b6fc5091799af51e3.jpg'),
       (14, 'C#', 'https://www.pngitem.com/pimgs/m/345-3450034_c-logo-hd-png-download.png'),
       (15, 'C', 'https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png'),
       (16, 'C++', 'https://www.techbaz.org/Course/img/cpp-logo.png'),
       (17, 'Laravel', 'https://brandslogos.com/wp-content/uploads/images/large/laravel-logo.png'),
       (18, 'Codeigniter', 'https://cdn.freebiesupply.com/logos/large/2x/codeigniter-logo-png-transparent.png'),
       (19, 'Symfony', 'https://cdn.freebiesupply.com/logos/large/2x/symfony-logo-png-transparent.png'),
       (20, 'Kotlin', 'https://cdn.freebiesupply.com/logos/thumbs/2x/kotlin-2-logo.png'),
       (21, 'ASP.NET', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSGu4R9Be5IDbtp0pl4EAr0tlj7SPIEXDBfA&usqp=CAU');